build:poduri.cpp adrese.cpp lego.cpp retea.cpp
	g++ poduri.cpp -o poduri
	g++ adrese.cpp -o adrese
	g++ lego.cpp -o lego
	g++ retea.cpp -o retea

run-p1:      # nume necesar
	./poduri
run-p2:      # nume necesar
	./adrese
run-p3:
	./lego   # nume necesar
run-p4:
	./retea
clean:		 # nume necesar
	rm -rf poduri adrese lego retea
